a = int(input("Enter the first number = "))
b = int(input("Enter the second number = "))
print(a, ' + ', b, '= {:,}'.format(a + b ))
print(a, ' - ', b, '= {:,}'.format(a - b ))
print(a, ' * ', b, '= {:,}'.format(a * b ))
print(a, ' / ', b, '= {:,.2f}'.format(a / b ))
print(a, ' // ', b, '= {:,}'.format(a // b ))
print(a, ' % ', b, '= {:,}'.format(a % b ))
print(a, ' ** ', b, '= {:,}'.format(a ** b ))